[workspace]
authors = ["Fernando Ferraz Ribeiro <ffribeiro@gmail.com>"]
channels = ["conda-forge"]
name = "intro_topografia"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.14"

[pypi-dependencies]
zensical = ">=0.0.29, <0.0.30"
